name: daytonrjohnson
static_sites:
- name: daytonrjohnson-frontend
  github:
    branch: deploy/digital-ocean
    deploy_on_push: true
    repo: idifyable/daytonrjohnson-v2
  environment_slug: html
  build_command: 'yarn build'
  source_dir: './build/static'
  envs: [ 'PUBLIC_URL=daytonrjohnson-v-2-nqkrm.ondigitalocean.app' ]
