name: daytonrjohnson
region: nyc
routes:
  - path: /
static_sites:
  - environment_slug: html
    name: daytonrjohnson-frontend
    build_command: 'yarn build'
    output_dir: './build'
    github:
      branch: deploy/digital-ocean
      deploy_on_push: true
      repo: idifyable/daytonrjohnson-v2
    envs:
      - key: PUBLIC_URL
        value: 'daytonrjohnson-v-2-nqkrm.ondigitalocean.app'
