name: daytonrjohnson-nextjs
region: nyc
static_sites:
  - environment_slug: html
    name: daytonrjohnson-frontend-nextjs
    build_command: 'yarn build'
    output_dir: '/out'
    github:
      branch: feature/convert-to-nextjs
      deploy_on_push: false
      repo: idifyable/daytonrjohnson-v2
    envs:
      - key: REACT_APP_GOOGLE_ANALYTICS_ID
        value: 'UA-55555555-5'
    routes:
      - path: /