name: daytonrjohnson
region: nyc
static_sites:
  - environment_slug: html
    name: daytonrjohnson-frontend-nextjs
    build_command: 'yarn build'
    output_dir: '/out'
    github:
      branch: deploy/live
      deploy_on_push: false
      repo: idifyable/daytonrjohnson-v2
    envs:
      - key: REACT_APP_GOOGLE_ANALYTICS_ID
        value: 'UA-96169555-2'
    routes:
      - path: /
domains:
  - domain: www.daytonrjohnson.com
    type: PRIMARY
    wildcard: true
