name: daytonrjohnson
static_sites:
  - environment_slug: html
    name: daytonrjohnson-frontend
    github:
      branch: deploy/digital-ocean
      deploy_on_push: true
      repo: idifyable/daytonrjohnson-v2
    envs:
      - key: PUBLIC_URL
      - value: 'daytonrjohnson-v-2-nqkrm.ondigitalocean.app'
    build_command: 'yarn build'
    output_dir: 'build'
