name: daytonrjohnson
region: nyc
static_sites:
  - environment_slug: html
    name: daytonrjohnson-frontend
    build_command: 'yarn build'
    output_dir: '/build'
    github:
      branch: deploy/live
      deploy_on_push: true
      repo: idifyable/daytonrjohnson-v2
    envs:
      - key: PUBLIC_URL
        value: 'https://daytonrjohnson-4ot6g.ondigitalocean.app'
      - key: REACT_APP_GOOGLE_ANALYTICS_ID
        value: 'UA-96169555-2'
    routes:
      - path: /
domains:
  - domain: www.daytonrjohnson.com
    type: PRIMARY
    wildcard: true